name: onnx_genai
description: "Wrapper for OnnxRuntime GenAI library."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^13.0.0

ffigen:
  name: onnx_genai
  output: lib/generated_bindings.dart
  headers:
    entry-points:
      - 'include/ort_genai_c.h'

flutter:
  assets:
    - assets/

